agent:
  machine_id: "desktop-dev-machine"
  location: "local-dev"
  sampling_rate: "100ms"
buffering:
  hot_buffer:
    capacity: 1048576 # 1MB
  warm_buffer:
    path: "/var/tmp/cnc-agent/warm.buffer"
    size: 10485760 # 10MB
  cold_buffer:
    path: "/var/tmp/cnc-agent/cold.log"
    max_size: 104857600 # 100MB
  batching:
    size: 100
    timeout: "200ms"
nats:
  url: "nats://localhost:4222"
  stream: "CNC_DATA"
  subject_prefix: "CNC.EDGE"
